### ISSUE TITLE
Cannot run doh-stub on ArchLinux, NPN extension not supported

### ISSUE THREAD

**Issue by maz-1** [facebookexperimental/doh-proxy#62]
```
[ling@archlinux Accesser]$ doh-stub \
>     --listen-port 5553 \
>     --listen-address ::1 \
>     --domain foo.bar \
>     --remote-address ::1
2019-04-24 21:03:57,586:     INFO: Starting UDP server
2019-04-24 21:03:57,586:    DEBUG: Opening connection to foo.bar
Traceback (most recent call last):
  File "/usr/bin/doh-stub", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/dohproxy/stub.py", line 40, in main
    loop.run_until_complete(proto.setup_client())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/dohproxy/client_protocol.py", line 34, in setup_client
    cafile=self.args.cafile
  File "/usr/lib/python3.7/site-packages/dohproxy/utils.py", line 131, in create_custom_ssl_context
    sslctx.set_npn_protocols(constants.DOH_H2_NPN_PROTOCOLS)
  File "/usr/lib/python3.7/ssl.py", line 434, in set_npn_protocols
    self._set_npn_protocols(protos)
NotImplementedError: The NPN extension requires OpenSSL 1.0.1 or later.
```

**Comment by maz-1** [comment]
openssl version: 1.1.1.b
python version: 3.7.3
doh-proxy version: 0.0.8

**Comment by maz-1** [comment]
It seems that openssl dropped npn support since 1.1.1 https://github.com/python/cpython/blob/8bb3230149538c25c1bacced5e64a3c071475f73/Modules/_ssl.c#L172

**Comment by chantra** [comment]
Hi @maz-1

Thanks. Let’s remove support from DoH-proxy. Feel free to submit a PR.

**Comment by chantra** [comment]
Essentially removing this line: https://github.com/facebookexperimental/doh-proxy/blob/master/dohproxy/utils.py#L131 and adapting the unittests.

**Comment by chantra** [comment]
v0.0.9, which contains the fix, was pushed to pip
