### ISSUE TITLE
aioh2 not compatible with Python 3.7

### ISSUE THREAD

**Issue by wlnirvana** [facebookexperimental/doh-proxy#93]
doh-proxy depends on aioh2, which uses the keyword (in Python 3.7) `async`.

```
$  ~ doh-client  \
    --domain dns.dnsoverhttps.net \
    --qname sigfail.verteiltesysteme.net \
    --dnssec
Traceback (most recent call last):
  File "/home/pi/.local/bin/doh-client", line 5, in <module>
    from dohproxy.client import main
  File "/home/pi/.local/lib/python3.7/site-packages/dohproxy/client.py", line 12, in <module>
    from dohproxy import client_protocol, utils
  File "/home/pi/.local/lib/python3.7/site-packages/dohproxy/client_protocol.py", line 10, in <module>
    import aioh2
  File "/home/pi/.local/lib/python3.7/site-packages/aioh2/__init__.py", line 2, in <module>
    from .helper import *
  File "/home/pi/.local/lib/python3.7/site-packages/aioh2/helper.py", line 89
    async_task = asyncio.async
```

**Comment by chantra** [comment]
@wlnirvana yeah, this is unfortunate but aioh2 does not seem to be maintained anymore. #63 has some workaround for you.

**Comment by chantra** [comment]
specifically https://github.com/facebookexperimental/doh-proxy/issues/63#issuecomment-590056284
